[amplifier_component]
# pem format cert
identity = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
'''
url = "https://amplifier-devnet-amplifier.devnet.axelar.dev/"
chain = "solana-devnet"

[relayer_engine]
[relayer_engine.health_check]
bind_addr = "0.0.0.0:3000"

[solana_listener_component]
solana_rpc = "https://api.devnet.solana.com"
