tickrate_secs = 5

env_filters = [
  "common=info",
  "storage_bus=info",
  "supervisor=info",
  "amplifier_ingester=info",
  "amplifier_subscriber=info",
]

[telemetry]
otlp_endpoint = "http://localhost:4317"
otlp_transport = "grpc"

[nats]
urls = ["nats://localhost:4222"]
connection_timeout_secs = 30

stream_name = "events"
stream_subject = "events.>"
stream_description = "Stream for all system events"

consumer_description = "Event processor"
deliver_group = "event-processors"

[gcp]
redis_connection = "redis://127.0.0.1/"
tasks_topic = "amplifier-tasks"
tasks_subscription = "amplifier-tasks-sub"
events_topic = "amplifier-events"
events_subscription = "amplifier-events-sub"
ack_deadline_secs = 10

[gcp.kms]
project_id = "axelar-relayer"
location = "global"
keyring = "amplifier_api_keyring"
cryptokey = "amplifier_api_signing_key"

[amplifier_component]
# pem format cert
tls_public_certificate = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
'''
# pem format cert
identity = '''
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
'''
url = "https://amplifier-devnet-amplifier.devnet.axelar.dev/"
chain = "starknet-devnet-v1"
get_chains_limit = 100
invalid_healthchecks_before_shutdown = 100

[health_check_server]
port = 8080
