apiVersion: 1

datasource:
  name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  version: 1
  editable: true
  isDefault: false
  jsonData:
    timeInterval: 15s
    httpMethod: GET
  secureJsonData: {}
