[package]
name = "amplifier-ingester"
edition.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
relayer-amplifier-api-integration.workspace = true
supervisor.workspace = true
tracing.workspace = true
eyre.workspace = true
storage-bus = { workspace = true, features = ["consumer-interfaces"] }
futures.workspace = true

[lints]
workspace = true
