name: "Setup Repo Action"
description: "A reusable composite action that setups rust and other common tasks"
inputs:
  toolchain:
    description: "An example input parameter"
    required: false
    default: "1.90.0"

runs:
  using: "composite"
  steps:
    - name: Install rust (stable)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: "rustfmt,clippy,cargo,llvm-tools-preview"
    - name: Install rust (nightly)
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: "rustfmt"
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
