[package]
name = "common"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ctrlc.workspace = true
tokio-util.workspace = true

[lints]
workspace = true

