[package]
name = "bin-util"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
eyre.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
futures.workspace = true
opentelemetry.workspace = true

machine-info = "1.0.9"
ctrlc = "3"
config = "0.15"
opentelemetry-otlp = { version = "0.29", features = ["metrics", "grpc-tonic"] }
opentelemetry_sdk = "0.29"
# TODO: update when compatible release is made
opentelemetry-system-metrics = { git = "https://github.com/haixuanTao/opentelemetry-system-metrics" }
opentelemetry-semantic-conventions = {version = "0.29", features = ["semconv_experimental"]}
opentelemetry-resource-detectors = "0.8"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
  "registry",
] }
tracing-opentelemetry = "0.30"
# serde_derive = "1.0"
axum = "0.8"

[dev-dependencies]
reqwest.workspace = true

[lints]
workspace = true

[features]
