[package]
name = "amplifier-api"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
bigint-u64 = []
bigint-u128 = []

[dependencies]
infrastructure = { workspace = true, features = ["publisher-interfaces"] }

base64.workspace = true
tracing.workspace = true
redact.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
typed-builder.workspace = true
rustls.workspace = true
hex.workspace = true

futures.workspace = true
progenitor-client = "0.11.0"
regress = "0.10.4"
reqwest = { workspace = true, features = ["json", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
indexmap = { version = "2.11", features = ["serde"] }
borsh = { workspace = true, features = ["derive", "indexmap" ]}
chrono = { workspace = true, features = ["serde"] }

bnum = "0.13"
simd-json = "0.15"
# reqwest-tracing = "0.5.7"
# reqwest-middleware = "0.4.2"
opentelemetry = "0.30.0"
tracing-opentelemetry = "0.31.0"

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
tokio.workspace = true
serde_json.workspace = true
eyre.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
prettyplease = "0.2.37"
progenitor = "0.11.0"
serde = "1.0.219"
serde_yaml = "0.9.34"
syn = "2.0.106"
eyre.workspace = true
# reqwest-middleware = "0.4.2"
reqwest = { version = "0.12", features = ["json" ] }
quote = "1.0"
opentelemetry = "0.30.0"
tracing-opentelemetry = "0.31.0"
tracing = { version = "0.1" }


[lints]
workspace = true

[[example]]
name = "healthcheck"
path = "examples/healthcheck.rs"
doc-scrape-examples = true
